# - Find Chunks And Tasks
# Find the native ChunksAndTasks headers and libraries.
#
#  CHUNKSANDTASKS_INCLUDE_DIRS - where to find hiredis.h, etc.
#  CHUNKSANDTASKS_LIBRARIES    - List of libraries when using hiredis.
#  CHUNKSANDTASKS_FOUND        - True if hiredis found.

# Look for the header file.
FIND_PATH(CHUNKSANDTASKS_INCLUDE_DIR NAMES chunks_and_tasks.h)

# Look for the library.
FIND_LIBRARY(CHUNKSANDTASKS_LIBRARY NAMES cht libcht )

# handle the QUIETLY and REQUIRED arguments and set CHUNKSANDTASKS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHUNKSANDTASKS DEFAULT_MSG CHUNKSANDTASKS_LIBRARY CHUNKSANDTASKS_INCLUDE_DIR)

# Copy the results to the output variables.
IF(CHUNKSANDTASKS_FOUND)
  SET(CHUNKSANDTASKS_LIBRARIES ${CHUNKSANDTASKS_LIBRARY})
  SET(CHUNKSANDTASKS_INCLUDE_DIRS ${CHUNKSANDTASKS_INCLUDE_DIR})
ELSE(CHUNKSANDTASKS_FOUND)
  SET(CHUNKSANDTASKS_LIBRARIES)
  SET(CHUNKSANDTASKS_INCLUDE_DIRS)
ENDIF(CHUNKSANDTASKS_FOUND)

MARK_AS_ADVANCED(CHUNKSANDTASKS_INCLUDE_DIR CHUNKSANDTASKS_LIBRARY)
